### ISSUE TITLE
Error with Jest Test

### ISSUE THREAD

**Issue by PanchoutNathan** [jitsi/jitsi-meet-react-sdk#24]
Hi all ! 

I'm trying to test my app with Jest and using the sdk. However, as soon as I try to test a component using JitsiMeeting, impossible.
Just in case it was my setup, I started from scratch with a blank CRA project, I just installed the SDK, it does the same.

Help :/ 

` ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/nathanpanchout/Documents/Societé/dossier sans titre/jitsi-test/node_modules/@jitsi/react-sdk/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './components';
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import * as React from 'react';
    > 2 | import {JitsiMeeting} from "@jitsi/react-sdk";
        | ^
      3 |
      4 | export interface VideoMeetingProps {
      5 | }

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/components/VideoMeeting/VideoMeeting.tsx:2:1)
      at Object.<anonymous> (src/components/VideoMeeting/VideoMeeting.test.tsx:3:1)`

**Comment by ivnxyz** [comment]
Hey! I'm facing the same problem. Were you able to solve it?
